### ISSUE TITLE
 Unable to get property 'classList' of undefined or null reference

### ISSUE THREAD

**Issue by euriphides** [aaronbarker/css-variables-polyfill#11]
I get this error in the console, and it seems like maybe it stops processing, because only some of my variables have been replaced.

**Comment by CodeZeno** [comment]
I can only see this happening if your document does not have a body tag or you could be running the script too early.
Try placing the script just before the end body tag of your document.

**Comment by aaronbarker** [comment]
@euriphides can you provide an example codepen or something?

**Comment by euriphides** [comment]
Sorry, it took me a bit to get back to you, but I seem to have fixed it
now. Moving it to a lower position in the list of JS files on my page seems
to have done the trick. Thanks so much for being so responsive - I'm not
used to such prompt replies :)
