### ISSUE TITLE
Multiple Vars referenced in one line don't work

### ISSUE THREAD

**Issue by proteantech** [aaronbarker/css-variables-polyfill#6]
Something like this doesn't work:

:root {
  --lh_grey: pink;
  --lh_lightgrey: purple; //#f3f3f3
  --timezone-button-background: linear-gradient(to bottom, var(--lh_lightgrey) 0%, var(--lh_grey) 50%, var(--lh_lightgrey) 100%); // This doesn't work.
  --timezone-button-background: var(--lh_grey); // This does.
}

**Comment by DevGoslinga** [comment]
Reading the description: "This is an attempt at a very basic CSS variables (custom properties) polyfil. In reality this is more of a partial polyfill as it will not cover variables inside of variables."

It is a known limitation unfortunately. However, https://github.com/jhildenbiddle/css-vars-ponyfill does support this scenario.

**Comment by aaronbarker** [comment]
This should be addressed in 1.2
